land_dm_prop <- read.table("input/input_tablesJambi/land_dist_matrix_prop.csv", header=TRUE, sep=",")
colnames(land_dm_prop) = c("Kode I-O","Nama Sektor","Hutan Lahan Kering Primer","Hutan Lahan Kering Sekunder","Hutan Rawa Primer","Hutan Rawa Sekunder","Hutan Mangrove Primer","Hutan Mangrove Sekunder","Hutan Tanaman","Semak/Belukar","Belukar Rawa","Savana/Padang Rumput","Perkebunan","Pertanian Lahan Kering","Pertanian Lahan Kering + Semak","Transmigrasi","Sawah","Tambak","Tanah Terbuka","Pertambangan","Permukiman","Tubuh Air","Rawa","Pelabuhan Udara/Laut","Awan")
land_dm <- read.table("input/input_tablesJambi/land_dist_matrix.csv", header=TRUE, sep=",")
colnames(land_dm) = c("Kode I-O","Nama Sektor", "Kategori","Hutan Lahan Kering Primer","Hutan Lahan Kering Sekunder","Hutan Rawa Primer","Hutan Rawa Sekunder","Hutan Mangrove Primer","Hutan Mangrove Sekunder","Hutan Tanaman","Semak/Belukar","Belukar Rawa","Savana/Padang Rumput","Perkebunan","Pertanian Lahan Kering","Pertanian Lahan Kering + Semak","Transmigrasi","Sawah","Tambak","Tanah Terbuka","Pertambangan","Permukiman","Tubuh Air","Rawa","Pelabuhan Udara/Laut","Awan")
land_demand <- read.table("input/input_tablesJambi/land_demand2017.csv", header=TRUE, sep=",")
colnames(land_demand) = c("Nama Sektor", "Kategori", "Permintaan Lahan")
land_pc <- read.table("input/input_tablesJambi/land_pc2017.csv", header=TRUE, sep=",")
colnames(land_pc) = c("Nama Sektor", "Kategori", "LPC (Juta Rupiah/Ha)")
land_rc <- read.table("input/input_tablesJambi/land_rc2017.csv", header=TRUE, sep=",")
colnames(land_rc) = c("Nama Sektor", "Kategori", "LRC (Ha/Juta Rupiah)")
