
selectedProv<-"SumBar"
datapath <- paste0("data/", selectedProv, "/")
userFolder <- paste0(datapath, username)
if(!dir.exists(userFolder)) dir.create(userFolder, mode = 777)
# system(paste0("chmod -R 777 ", userFolder))

Prov="JaBar"
LDMProp<-read.csv(paste0("olah_LDMProp/",Prov,"_LDMProp.csv"))
sum<-as.matrix(colSums(LDMProp))
saveRDS(LDMProp, file=paste0("data/",Prov,"/LDMProp"))
# Prov="KepRi"
# LDMProp<-read.csv(paste0("olah_LDMProp/",Prov,"_LDMProp.csv"))
tupla<-ncol(LDMProp)
LU_tahun<-read.csv(paste0("olah_LU_tahun/",Prov,"_LU_tahun.csv"),header = TRUE)
tupla2<-nrow(LU_tahun)
saveRDS(LU_tahun,file=paste0("data/",Prov,"/LU_tahun"))

Prov="JaBar"
LDMProp<-read.csv('data/JaBar/LDMProp.csv')
saveRDS(LDMProp,"data/JaBar/LDMProp")
LU_tahun<-read.csv("data/JaBar/LU_tahun.csv")
saveRDS(LU_tahun,"data/JaBar/LU_tahun")


selectedProv<-"JaBar"
datapath <- paste0("data/", selectedProv, "/")

sector <- readRDS(paste0(datapath, "sector"))
indem <- readRDS(paste0(datapath, "indem"))
findem <- readRDS(paste0(datapath, "findem"))
addval <- readRDS(paste0(datapath, "addval"))
labour <- readRDS(paste0(datapath, "labour"))
energy <- readRDS(paste0(datapath, "energy"))
waste <- readRDS(paste0(datapath, "waste"))
ef_energy <- readRDS(paste0(datapath, "ef_energy"))
ef_waste <- readRDS(paste0(datapath, "ef_waste"))
findemcom <- readRDS(paste0(datapath, "findemcom"))
addvalcom <- readRDS(paste0(datapath, "addvalcom"))
population <- readRDS(paste0(datapath, "population"))
otherEm <- readRDS(paste0(datapath, "otherEm"))
# landDemand <- readRDS(paste0(datapath, "landDemand"))
# landDemand_prop <- readRDS(paste0(datapath, "landDemand_prop"))
# landTable <- readRDS(paste0(datapath, "landTable"))
I_A <- readRDS(paste0(datapath, "I_A"))
leontief <- readRDS(paste0(datapath, "leontief"))
GDPAll <- readRDS(paste0(datapath, "GDPAll"))
linkagesTable <- readRDS(paste0(datapath, "linkagesTable"))
multiplierAll <- readRDS(paste0(datapath, "multiplierAll"))
periodIO <- readRDS(paste0(datapath, "periodIO"))
LU_tahun<-readRDS(paste0(datapath,"LU_tahun"))
LDMProp_his<-readRDS(paste0(datapath,"LDMProp"))
rtffile <- readRDS(paste0(datapath, "rtffile"))

write.csv(sector, "data/JaBar/dataPrep/sector.csv")
write.csv(indem, "data/JaBar/dataPrep/indem.csv")
write.csv(findem, "data/JaBar/dataPrep/findem.csv")
write.csv(addval, "data/JaBar/dataPrep/addval.csv")
write.csv(labour, "data/JaBar/dataPrep/labour.csv")
write.csv(energy, "data/JaBar/dataPrep/energy.csv")
write.csv(waste, "data/JaBar/dataPrep/waste.csv")
write.csv(ef_energy, "data/JaBar/dataPrep/ef_energy.csv")
write.csv(ef_waste, "data/JaBar/dataPrep/ef_waste.csv")
write.csv(findemcom, "data/JaBar/dataPrep/findemcom.csv")
write.csv(addvalcom, "data/JaBar/dataPrep/addvalcom.csv")
write.csv(population, "data/JaBar/dataPrep/population.csv")
write.csv(otherEm, "data/JaBar/dataPrep/otherEm.csv")
# landDemand <- readRDS(paste0(datapath, "landDemand"))
# landDemand_prop <- readRDS(paste0(datapath, "landDemand_prop"))
# landTable <- readRDS(paste0(datapath, "landTable"))
write.csv(I_A, "data/JaBar/dataPrep/I_A.csv")
write.csv(leontief, "data/JaBar/dataPrep/leontief.csv")
write.csv(GDPAll, "data/JaBar/dataPrep/GDPAll.csv")
 write.csv(linkagesTable, "data/JaBar/dataPrep/linkagesTable.csv")
 write.csv(multiplierAll, "data/JaBar/dataPrep/multiplierAll.csv")
write.csv(periodIO, "data/JaBar/dataPrep/periodIO.csv")
write.csv(LU_tahun, "data/JaBar/dataPrep/LU_tahun.csv")
write.csv(LDMProp_his, "data/JaBar/dataPrep/LDMProp.csv")
write.csv(rtffile, "data/JaBar/dataPrep/rtffile.csv")

